FROM oven/bun:1.3.9

WORKDIR /app

COPY package.json bun.lock turbo.json biome.json ./
COPY apps/api/package.json ./apps/api/package.json
COPY apps/web/package.json ./apps/web/package.json
COPY packages/database/package.json ./packages/database/package.json
COPY packages/types/package.json ./packages/types/package.json

RUN bun install

COPY apps ./apps
COPY packages ./packages

EXPOSE 8000

CMD ["bun", "run", "--filter=@mindscribe/api", "dev"]
